### ISSUE TITLE
CR009: Redesign sherab.org layout to be more user-friendly

### ISSUE THREAD

**Issue by HoaDinh86** [OpenPecha/sherab.org#12]
**Discription:**
Redesign sherab.org layout to be more user-friendly

**Suggest Solution:**
- Brainstorm ideas about the new layout: 
   References: [https://www.edx.org/school/harvardx](https://www.edx.org/school/harvardx); [https://www.coursera.org/](https://www.coursera.org/)
- Look for a designer freelancer - Prepare job requirement
- Final decision for a new layout
- Update code
- Test
- Release new layout

**Layout suggestion:**
[https://www.figma.com/design/f3DdaBNbgT0xm6Hp8b6ZUt/Landing-Page?node-id=0-1&p=f&t=wgIx4AnLLUW15vPV-0](https://www.figma.com/design/f3DdaBNbgT0xm6Hp8b6ZUt/Landing-Page?node-id=0-1&p=f&t=wgIx4AnLLUW15vPV-0)

New Logo: Manjushri Seed syllable Dhīḥ(धीः) inside dharma wheel

## Subtask

- [x] Header Navbar top
- [x] Header seacher bar
- [x] Client's feedback section
- [x] Frequantly asked question seaction
- [x] Footer section

## Completion Criteria
Changes in logo with header navbar design.
Changes according to the figma designs for seacher bar.

## Reviewer 

- [x] @HoaDinh86
